### ISSUE TITLE
Forge Update

### ISSUE THREAD

**Issue by gusnuf** [pjorg/sumo#12]
The forge is currently 1.1.0, as is master, but there are tags as high as 1.2.1.  Could you please publish the latest to the forge?  Thanks.

**Comment by pjorg** [comment]
Hi @gusnuf; I may eventually do this when I have time, but in the meantime you can use a Puppetfile to have r10k or Code Manager include the version of the module you want.

**Comment by lreed** [comment]
Hello,
I am making some minor additions to this module to make it more flexible for configs etc.
However I am building of the latest version here.  I need it to be available on Puppet Forge however.
If you don't think you are planning to update the version on the Forge, do you mind if I fork, and make my changes , and publish latest to the forge?  

Thanks!

**Comment by pjorg** [comment]
@lreed is there an outstanding pull request with your proposed changes?

**Comment by lreed** [comment]
I just submitted.  Thanks for looking!!  And I see the Travis CI stuff, awesone!

**Comment by pjorg** [comment]
Well, don't get too excited because I don't think the Travis stuff is working...

**Comment by ghoneycutt** [comment]
Hi @pjorg It would be great if the module would auto publish any tags to the forge.

Here's an example

https://github.com/sgnl05/sgnl05-sssd/blob/master/.travis.yml#L25-L35

And the docs

https://puppet.com/docs/puppet/6.2/modules_publishing.html#task-5977

https://docs.travis-ci.com/user/deployment/puppetforge/

**Comment by pjorg** [comment]
Having some cred problems here in `.travis.yml`. Maybe a bad encrypt operation the first time around?

**Comment by pjorg** [comment]
Anybody know of a way to test the password in `.travis.yml` without another release?

**Comment by ghoneycutt** [comment]
You could try deleting the tag then re-adding it

**Comment by pjorg** [comment]
Alright. Well. It worked...sort of. The Travis CI build failed, but only because apparently _both_ build jobs tried to upload the Forge update, and after the first one succeeded, the second one choked because the version already exists.

Not sure what to do about that. Need a Travis CI adult. @ghoneycutt, you there?

**Comment by ghoneycutt** [comment]
Created PR #19 based on another module we have working - https://github.com/sgnl05/sgnl05-sssd

**Comment by pjorg** [comment]
Awesome work, thanks @ghoneycutt. Version 1.3.3 passed in Travis and uploaded to Forge without issues.

**Comment by pjorg** [comment]
Well, if anyone wondered if I know what I am doing on GitHub, now they know for sure that I do not.

Forge release is now aligned to most recent GitHub release. Closing this.
